---
imports: C:\\Users\\amogus\\PycharmProjects\\pythonProject5\\db\\imports
movies: C:\\Users\\amogus\\PycharmProjects\\pythonProject5\\db\\movies
categories: C:\\Users\\amogus\\PycharmProjects\\pythonProject5\\db\\categories
actors: C:\\Users\\amogus\\PycharmProjects\\pythonProject5\\db\\actors
series: C:\\Users\\amogus\\PycharmProjects\\pythonProject5\\db\\series
studios: C:\\Users\\amogus\\PycharmProjects\\pythonProject5\\db\\studios
